version: '3'

services:
  ids-app:
    build: .
    image: intrusion-detection-system
    container_name: ids-app
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/app
    network_mode: host
    privileged: true  # Необходимо для доступа к сетевым интерфейсам
    restart: unless-stopped 